name: bookie

services:
  db:
    container_name: bookie_pg
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=unicorn
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=bookie
    ports:
      - 5432:5432
    volumes:
      - bookie_pg:/var/lib/postgresql/data
  redis:
    container_name: bookie_redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

volumes:
  bookie_pg:
    driver: local
